name: Deploy Angular Project to Firebase Hosting

on:
  push:
    branches:
      - deployment/frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install --legacy-peer-deps
      working-directory: ./frontend

    - name: Build Angular Project
      run: npm run build_prod
      working-directory: ./frontend

    - name: Deploy to Firebase Hosting
      run: firebase deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      working-directory: ./frontend
    
    
      